UID              :=  $(shell whoami)+$(TEST)+$(shell date +"%Y-%m-%d-%H:%M:%S.%N")
python SimulationAnalysis.py -stage sim_start -uid ${UID} -project ${PROJECT} -case ${TEST} -owner ${U} -user $(shell whoami) -path $(shell pwd) -level ${SIM_LEVEL};\
